"use client";

import Link from "next/link";
import { Activity, ArrowUpRight, Bot, Box, CheckCircle2, Coins, Database, GitFork, HeartPulse, RefreshCw, Server, Sparkles, Workflow } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { useRuntimeStatus } from "@/lib/api/runtime";
import { useWorkspace } from "@/lib/workspace/WorkspaceProvider";

export default function CommandCentrePage() {
  const { status, loading, refresh } = useRuntimeStatus();
  const { workspace } = useWorkspace();
  const services = status?.services ?? [];
  const ready = services.filter((service) => service.state === "online").length;
  const capabilityStates = status?.capabilityStates ?? {};
  const capabilityReady = Object.values(capabilityStates).filter((state) => state === "ready").length;

  return <div className="mx-auto max-w-[1680px] space-y-5 pb-12">
    <section className="relative overflow-hidden rounded-3xl border border-border-subtle bg-[#080d18] p-5 sm:p-7">
      <div className="pointer-events-none absolute -right-24 -top-24 h-64 w-64 rounded-full bg-accent-purple/10 blur-3xl" /><div className="pointer-events-none absolute -bottom-32 left-1/3 h-56 w-56 rounded-full bg-accent-cyan/10 blur-3xl" />
      <div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[0.28em] text-accent-cyan">VEYAAN / CONTROL PLANE</p><h1 className="mt-3 font-display text-3xl font-semibold tracking-tight text-white sm:text-4xl">Command Centre</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-text-muted">A truthful live view of the orchestration system, workspace data, and runtime capabilities.</p></div><Button size="sm" onClick={() => void refresh()} disabled={loading}><RefreshCw className={loading ? "h-4 w-4 animate-spin" : "h-4 w-4"} />Refresh status</Button></div>
    </section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile icon={Server} label="Services ready" value={services.length ? `${ready}/${services.length}` : "—"} detail={ready === services.length && services.length > 0 ? "All reported ready" : "Readiness is checked live"} tone="cyan" /><MetricTile icon={Database} label="Workspace data" value={status?.authenticated ? "Loaded" : "Locked"} detail={status?.authenticated ? "Authenticated session" : "Bearer token required"} tone="purple" /><MetricTile icon={Workflow} label="JCode capabilities" value={Object.keys(capabilityStates).length ? `${capabilityReady}/${Object.keys(capabilityStates).length}` : "—"} detail="Provider-gated execution" tone="green" /><MetricTile icon={HeartPulse} label="Gateway access" value={status?.authenticated ? "Verified" : "Locked"} detail="Runtime details require your workspace session" tone="amber" /></section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(18rem,0.75fr)]"><Card className="overflow-hidden"><CardHeader><div><CardTitle>System overview</CardTitle><p className="mt-1 text-xs text-text-muted">Live service topology and capability health.</p></div><Badge tone={loading ? "neutral" : ready > 0 ? "success" : "danger"}>{loading ? "Checking" : ready > 0 ? "Connected" : "Offline"}</Badge></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2">{services.map((service) => <ServiceTile key={service.name} name={service.name} detail={service.detail} state={service.state} />)}{!services.length && <div className="sm:col-span-2"><EmptyState title="No runtime response" description="Sign in, then refresh this view to read the workspace-scoped runtime status." /></div>}</div>{Object.keys(capabilityStates).length > 0 && <div className="mt-5 border-t border-border-subtle pt-5"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold text-white">Runner capability manifest</span><span className="font-mono text-[10px] text-text-muted">{capabilityReady} ready</span></div><div className="flex flex-wrap gap-2">{Object.entries(capabilityStates).map(([name, state]) => <Badge key={name} tone={state === "ready" ? "success" : state === "planned" ? "warning" : "danger"}>{name}: {state}</Badge>)}</div></div>}</CardContent></Card><Card><CardHeader><div><CardTitle>Activity stream</CardTitle><p className="mt-1 text-xs text-text-muted">Workspace events appear when authenticated.</p></div><Activity className="h-4 w-4 text-accent-cyan" /></CardHeader><CardContent><EmptyState title="No live activity" description={workspace ? "Workspace is connected; activity will appear when a workflow runs." : "Sign in to a workspace to receive projects, agents, approvals, and event updates."} locked={!workspace} /></CardContent></Card></section>

    <section className="grid gap-5 lg:grid-cols-3"><DataPanel icon={Bot} title="Top agents" href="/agents" detail={workspace ? "No agent records loaded" : "Workspace access required"} /><DataPanel icon={CheckCircle2} title="Approvals" href="/approvals" detail={workspace ? "No approval records loaded" : "Workspace access required"} /><DataPanel icon={Coins} title="Cost overview" href="/costs" detail={workspace ? "No cost records loaded" : "Cost data requires workspace access"} /></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><QuickAction icon={Sparkles} title="Ask Assistant" href="/assistant" /><QuickAction icon={GitFork} title="Open Workflow Studio" href="/workflows" /><QuickAction icon={Box} title="Inspect JCode" href="/sandboxes" /><QuickAction icon={ArrowUpRight} title="Connection settings" href="/settings" /></section>
  </div>;
}

function MetricTile({ icon: Icon, label, value, detail, tone }: { icon: typeof Server; label: string; value: string; detail: string; tone: "cyan" | "purple" | "green" | "amber" }) {
  const colors = { cyan: "text-accent-cyan bg-accent-cyan/10 border-accent-cyan/20", purple: "text-accent-purple bg-accent-purple/10 border-accent-purple/20", green: "text-status-success bg-status-success/10 border-status-success/20", amber: "text-status-warning bg-status-warning/10 border-status-warning/20" };
  return <Card className="p-4"><div className={`flex h-9 w-9 items-center justify-center rounded-xl border ${colors[tone]}`}><Icon className="h-4 w-4" /></div><p className="mt-4 text-xs text-text-muted">{label}</p><p className="mt-1 text-xl font-semibold text-white">{value}</p><p className="mt-1 text-[10px] text-text-muted">{detail}</p></Card>;
}

function ServiceTile({ name, detail, state }: { name: string; detail: string; state: string }) { const online = state === "online"; return <div className="rounded-2xl border border-border-subtle bg-bg-surface-2/60 p-4"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2.5"><span className={`h-2 w-2 shrink-0 rounded-full ${online ? "bg-status-success" : state === "offline" ? "bg-status-danger" : "bg-status-warning"}`} /><span className="truncate text-sm font-medium text-white">{name}</span></div><Badge tone={online ? "success" : state === "offline" ? "danger" : "warning"}>{state}</Badge></div><p className="mt-3 text-xs text-text-secondary">{detail}</p></div>; }
function DataPanel({ icon: Icon, title, href, detail }: { icon: typeof Bot; title: string; href: string; detail: string }) { return <Card className="min-h-44"><CardHeader><CardTitle className="flex items-center gap-2"><Icon className="h-4 w-4 text-accent-cyan" />{title}</CardTitle><Link href={href} aria-label={`Open ${title}`} className="text-text-muted hover:text-accent-cyan"><ArrowUpRight className="h-4 w-4" /></Link></CardHeader><CardContent><div className="flex min-h-20 items-center justify-center rounded-xl border border-dashed border-border-subtle text-center text-xs text-text-muted">{detail}</div></CardContent></Card>; }
function QuickAction({ icon: Icon, title, href }: { icon: typeof Sparkles; title: string; href: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-border-subtle bg-bg-surface-1 p-4 text-sm font-medium text-text-secondary transition-colors hover:border-accent-cyan/40 hover:text-white"><Icon className="h-4 w-4 text-accent-cyan" />{title}<ArrowUpRight className="ml-auto h-4 w-4 text-text-muted" /></Link>; }
